### ISSUE TITLE
[Research] Go modules

### ISSUE THREAD

**Issue by noot** [ChainSafeSystems/go-pre#4]
Are going to use Go 1.11 and create modules instead of packages? In case of repo rename in the future.

**Comment by ansermino** [comment]
Does this affect the dependencies we use? Or are all packages forward-compatible? (ie. they don't need to be using go 1.11)

**Comment by noot** [comment]
@dutterbutter is there any benefit to using go modules?  it seems more like it's for package management.

**Comment by dutterbutter** [comment]
The benefits of go modules that I am aware of are as follows:

- No need to put your code into the GOPATH (if you don’t want), you can have your go workspace where ever you please
- It can ingest dependency files from other dependency managers such as dep, glide, govendor
-  Go modules by default fetches code from version control systems (VCS) directly, so you can now specify versions in your `go.mod` file and whenever you run `go get` it will fetch that particular version
- Will be apart of the go standard upon go2 release

With the amount of critical dependencies we will be using I would recommend using go modules, you can look at opennetsys/go-substrate `go.mod` file as an example. 

To utilize go modules in your bash profile include `export GO111MODULE=on`

**Comment by ansermino** [comment]
Won't be using go mods for time being
